version: '3'

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    # volumes:
    #   - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql